version: '3'

services:
  ingester:
    restart: always
    image: amalthundiyil/cm-ingester:latest
    build:
      context: './src/ingester'
    container_name: cm-ingester
    command: sh -c "uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 80"
    environment:
      MAPS_API_KEY: ${MAPS_API_KEY}
      MONGO_URL: ${MONGO_URL}
    ports:
      - "8001:80"
    volumes:
      - .:/usr/app/src
  user:
    restart: always
    image: amalthundiyil/cm-user:latest
    build:
      context: './src/user'
    container_name: cm-user
    # command: sh -c "npm run start"
    environment:
      MONGO_URL: ${MONGO_URL}
      JWTPRIVATEKEY: ${JWTPRIVATEKEY}
    ports:
      - "8002:8000"
    volumes:
      - .:/usr/app/src

  offers:
    restart: always
    image: amalthundiyil/cm-offers:latest
    build:
      context: './src/offers'
    container_name: cm-offers
    # command: sh -c "npm run start"
    environment:
      MONGO_URL: ${MONGO_URL}
      JWTPRIVATEKEY: ${JWTPRIVATEKEY}
    ports:
      - "8003:8000"
    volumes:
      - .:/usr/app/src

volumes:
  data:
